mqtt:
  server: mqtt://127.0.0.1:1883 # mqtt's ip:port
  servername: 127.0.0.1 # server's ip
  username: ""
  password: ""
  clientId: ""
  certification: ""
  privatekey: ""
  caCert: ""
http:
  certification: ""
  privatekey: ""
  caCert: ""
configmap: /opt/kubeedge/deviceProfile.json
